apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: harbor.vgregion.se/education/quotes-service
    newName: harbor.vgregion.se/education/quotes-service
    newTag: 0.0.1
