apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: crackitty/quote-service
    newName: crackitty/quote-service
    newTag: 0.0.1
