apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  selector:
    app: quote-service
  ports:
    - port: 80
      name: web
      targetPort: 8001
    - port: 443
      name: https
      targetPort: 8001
